name: simple
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scroll_bottom_navigation_bar:
    path: ../..

flutter:
  uses-material-design: true