name: scroll_bottom_navigation_bar
description: This package allow hide or show bottom navigation bar while scrolling
version: 3.0.0
homepage: https://github.com/EdsonOnildoJR/scroll_bottom_navigation_bar

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scroll_bars_common: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
