name: scroll_app_bar
description: Hide or show app bar while scrolling. This package works without custom scroll view and slivers.
version: 1.0.3
homepage: https://github.com/edsonbonfim/scroll_bars/tree/master/scroll_app_bar
issue_tracker: https://github.com/edsonbonfim/scroll_bars/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scroll_bars_common:
    path: ../scroll_bars_common

dev_dependencies:
  flutter_test:
    sdk: flutter