name: scroll_bars_common
description: A common package to scroll bars packages. This package is not intended for direct use.
version: 1.0.0
homepage: https://github.com/EdsonOnildoJR/scroll_bars_common

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
